
version: 2.1

jobs:
  smoke-test:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: |
            if curl -s --head "https://google.com" 
            then
              echo "It worked!"
              echo 0
            else
              echo "It failed"
              echo 1
            fi

workflows:
  smoke-test-workflow:
    jobs:
      - smoke-test
