
version: 2.1

jobs:
  smoke-test:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - run: apk add --update curl
      - run:
          name: smoke test
          command: |
            URL="https://blog.udacityasdasdasd.com/"
            # Test if website exists
            if curl -s --head ${URL} 
            then
              return 0
            else
              return 1
            fi

workflows:
  smoke-test-workflow:
    jobs:
      - smoke-test
